# Generated by go2rpm 1.8.0
%bcond_without check

# https://github.com/awslabs/aws-go-multi-module-repository-tools
%global goipath         github.com/awslabs/aws-go-multi-module-repository-tools
%global commit          ca714c205071a4f44115d2fbf04fc3f74d53f1a1
%global debug_package %{nil}

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another pacage,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE LICENSE.txt NOTICE
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md README.md\\\
                        cmd/calculaterelease/README.md\\\
                        cmd/changelog/README.md\\\
                        cmd/editmoduledependency/README.md\\\
                        cmd/moduleversion/README.md\\\
                        cmd/updaterequires/README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p -b 2
Summary:        None

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE LICENSE.txt NOTICE
%doc CODE_OF_CONDUCT.md CONTRIBUTING.md README.md cmd/calculaterelease/README.md
%doc cmd/changelog/README.md cmd/editmoduledependency/README.md
%doc cmd/moduleversion/README.md cmd/updaterequires/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
