# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/bmatcuk/doublestar
%global goipath         github.com/bmatcuk/doublestar
Version:                4.0.2

%gometa

%global common_description %{expand:
Implements support for double star (**) matches in golang's path.Match and
filepath.Glob.}

%global golicenses      LICENSE
%global godocs          examples README.md UPGRADING.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Implements support for double star (**) matches in golang's path.Match and filepath.Glob

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed May 25 2022 Anthony Rabbito <hello@anthonyrabbito.com> - 4.0.2-1
- Initial package
