# Generated by go2rpm 1.8.1
%bcond_without check

# https://github.com/terraform-linters/tflint
%global goipath         github.com/terraform-linters/tflint
Version:                0.41.0

%gometa -f

%global common_description %{expand:
A Pluggable Terraform Linter.}

%global golicenses      LICENSE terraform/LICENSE terraform/ipaddr/LICENSE\\\
                        terraform/ipaddr/PATENTS
%global godocs          docs CHANGELOG.md README.md example cmd/test-\\\
                        fixtures/arguments/README\\\
                        integrationtest/cli/multiple_files/README.md example\\\
                        plugin/test-fixtures/signatures/checksums.txt.sig\\\
                        terraform/README.md terraform/ipaddr/README.md\\\
                        tflint/test-fixtures/is_config_file/README

%global goname  tflint
Name:           %{goname}
Release:        %autorelease
Summary:        A Pluggable Terraform Linter

License:        BSD-3-Clause and MPL-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/tflint %{goipath}
for cmd in plugin/stub-generator/sources/customrulesettesting plugin/stub-generator/sources/testing plugin/stub-generator/sources/foo integrationtest/init plugin/stub-generator/sources/bar plugin/stub-generator integrationtest/langserver integrationtest/cli integrationtest/bundled integrationtest/inspection; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE terraform/LICENSE terraform/ipaddr/LICENSE
%license terraform/ipaddr/PATENTS
%doc docs CHANGELOG.md README.md example cmd/test-fixtures/arguments/README
%doc integrationtest/cli/multiple_files/README.md example
%doc plugin/test-fixtures/signatures/checksums.txt.sig terraform/README.md
%doc terraform/ipaddr/README.md tflint/test-fixtures/is_config_file/README
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
