# golang-github-int128-oauth2cli.spec
# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/int128/oauth2cli
%global goipath         github.com/int128/oauth2cli
Version:                1.14.0

%gometa

%global common_description %{expand:
Go package of OAuth 2.0 authorization for command line tools, which allows
simple authorization flow for better UX.}

%global golicenses      LICENSE
%global godocs          docs example README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go package of OAuth 2.0 authorization for command line tools, which allows simple authorization flow for better UX

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog

