# Generated by go2rpm 1.8.0
%bcond_without check

# https://github.com/fluxcd/helm-controller
%global goipath         github.com/fluxcd/helm-controller
Version:                0.23.1

%gometa -f

%global common_description %{expand:
The GitOps Toolkit Helm reconciler, for declarative Helming.}

%global golicenses      LICENSE
%global godocs          docs CHANGELOG.md CODE_OF_CONDUCT.md DEVELOPMENT.md\\\
                        README.md hack/boilerplate.go.txt

Name:           %{goname}
Release:        %autorelease
Summary:        The GitOps Toolkit Helm reconciler, for declarative Helming

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/helm-controller %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs CHANGELOG.md CODE_OF_CONDUCT.md DEVELOPMENT.md README.md
%doc hack/boilerplate.go.txt
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
