# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/google/gops
%global goipath         github.com/google/gops
Version:                0.3.25

%gometa -f

%global common_description %{expand:
A tool to list and diagnose Go processes currently running on your system.}

%global golicenses      LICENSE
%global godocs          examples README.md

%global goname  gops
Name:           %{goname}
Release:        %autorelease
Summary:        A tool to list and diagnose Go processes currently running on your system

License:        BSD-3-Clause
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/gops %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc examples README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
