# Generated by go2rpm 1.8.1
%bcond_without check

# https://github.com/mikefarah/yq
%global goipath         github.com/mikefarah/yq
Version:                4.27.5
%gometa -f

%global common_description %{expand:
Yq is a portable command-line YAML, JSON, XML, CSV and properties processor.}

%global golicenses      LICENSE
%global godocs          examples CODE_OF_CONDUCT.md CONTRIBUTING.md README.md\\\
                        how-it-works.md release_instructions.txt\\\
                        release_notes.txt debian/changelog doc
%global goname  yq
Name:           %{goname}
Release:        %autorelease
Summary:        Yq is a portable command-line YAML, JSON, XML, CSV and properties processor

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/yq %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc examples CODE_OF_CONDUCT.md CONTRIBUTING.md README.md how-it-works.md
%doc release_instructions.txt release_notes.txt debian/changelog doc
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
