# Generated by go2rpm 1.6.0
# Various dbus and keyring errors
%bcond_without check
%global debug_package %{nil}
%global with_check 1

# https://github.com/zalando/go-keyring
%global goipath         github.com/zalando/go-keyring
Version:                0.2.1

%gometa -f

%global common_description %{expand:
Cross-platform keyring interface for Go.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md SECURITY.md

Name:           %{goname}
Release:        %autorelease
Summary:        Cross-platform keyring interface for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  gnome-keyring
BuildRequires:  dbus-x11
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
# test require dbus and gnome-keyring daemonized and configured
# may be possible to do?
for test in "TestDeleteNonExisting" "TestDelete" "TestGetNonExisting" "TestGet" "TestGetSingleLineHex" "TestGetUmlaut" \
"TestGetMultiLine" "TestSet" \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
