# Generated by go2rpm 1.6.0
# Various dbus and keyring errors
%bcond_without check
%global debug_package %{nil}

# https://github.com/zalando/go-keyring
%global goipath         github.com/zalando/go-keyring
Version:                0.2.1

%gometa

%global common_description %{expand:
Cross-platform keyring interface for Go.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md SECURITY.md

Name:           %{goname}
Release:        %autorelease
Summary:        Cross-platform keyring interface for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  dbus-x11
BuildRequires:  gnome-keyring
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
