# Generated by go2rpm 1.6.0
%bcond_with check
%global debug_package %{nil}

# https://github.com/keybase/go-ps
%global goipath         github.com/keybase/go-ps
%global commit          91aafc93ba19d1988cff338c1929d35b6c6f5b50

%gometa

%global common_description %{expand:
Find, list, and inspect processes from Go (golang).}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease
Summary:        Find, list, and inspect processes from Go (golang)

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed May 25 2022 Anthony Rabbito <hello@anthonyrabbito.com> - 0-0.2.20220525git91aafc9
- Disable tests

* Wed May 25 2022 Anthony Rabbito <hello@anthonyrabbito.com> - 0-0.2.20220525git91aafc9
- Initial package
