# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/keybase/go-ps
%global goipath         github.com/keybase/go-ps
%global commit          91aafc93ba19d1988cff338c1929d35b6c6f5b50

%gometa -f

%global common_description %{expand:
Find, list, and inspect processes from Go (golang).}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Find, list, and inspect processes from Go (golang)

License:        MIT

URL:            %{gourl}
Source:         %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
# github.com/keybase/go-ps
#./process_openbsd.go:26:1: misplaced +build comment
sed -i '/\/\/ +build ignore/d' process_openbsd.go
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
