# Generated by go2rpm 1.8.0
%bcond_without check

# https://github.com/tcnksm/go-latest
%global goipath         github.com/tcnksm/go-latest
%global commit          e3007ae9052ed85144087e7392e4c3fbc07962fa

%gometa

%global common_description %{expand:
Simple way to check version is latest or not from various sources in Golang.}

%global golicenses      LICENSE
%global godocs          doc CHANGELOG.md README.md latest/README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Simple way to check version is latest or not from various sources in Golang

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in latest; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc doc CHANGELOG.md README.md latest/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
