# Generated by go2rpm 1.8.0
%bcond_without check

# https://github.com/fluxcd/flux2
%global goipath         github.com/fluxcd/flux2
%global goname          flux2
Version:                0.32.0

%gometa

%global common_description %{expand:
Open and extensible continuous delivery solution for Kubernetes. Powered by
GitOps Toolkit.}

%global golicenses      LICENSE
%global godocs          docs CODE_OF_CONDUCT.md CONTRIBUTING.md README.md\\\
                        action/README.md install/README.md\\\

Name:           %{goname}
Release:        %autorelease
Summary:        Open and extensible continuous delivery solution for Kubernetes. Powered by GitOps Toolkit

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
# RFCs change often, and create a burden for godocs
rm -r rfcs/

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs CODE_OF_CONDUCT.md CONTRIBUTING.md README.md action/README.md
%doc install/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog

