# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/iancoleman/orderedmap
%global goipath         github.com/iancoleman/orderedmap
Version:                0.2.0

%gometa -f

%global common_description %{expand:
Orderedmap is a golang map where the keys keep the order that they're added. It
can be de/serialized from/to JSON. It's based closely on the python
collections.OrderedDict.}

%global golicenses      LICENSE
%global godocs          readme.md

Name:           %{goname}
Release:        %autorelease
Summary:        Orderedmap is a golang map where the keys keep the order that they're added. It can be de/serialized from/to JSON. It's based closely on the python collections.OrderedDict

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
