# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/withfig/autocomplete-tools
# Multi-language mono-repo intergrating the "fig" shell in various ways
# This package just cares about the ipath of github.com/withfig/autocomplete-tools/integrations/cobra
# It was recetently split from integrations/cobra and hasn't received a tag yet.
%global goipath         github.com/withfig/autocomplete-tools/integrations/cobra
%global gosourcedir0    %{_builddir}/%{topdir}/integrations/cobra
Version:                0
%global commit          41b7753859e9773a4fd0fbda393f2db9ddb0b952

%gometa -f

%global common_description %{expand:
Cobra intergration for the fig shell.}

%global golicenses      LICENSE integrations/cobra/LICENSE
%global godocs          README.md integrations/cobra/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Command line tools for working with Fig autocomplete specs

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
