# golang-github-orisano-pixelmatch.spec
# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/orisano/pixelmatch
%global goipath         github.com/orisano/pixelmatch
%global commit          fb0b55479cde89fd42234927a9e27786d459dd89

%gometa

%global common_description %{expand:
Mapbox/pixelmatch ports for go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Mapbox/pixelmatch ports for go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog

