# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/DHowett/go-plist
%global goipath         howett.net/plist
%global forgeurl        https://github.com/DHowett/go-plist
Version:                1.0.0

%gometa

%global common_description %{expand:
A pure Go Apple Property List transcoder.}

%global golicenses      LICENSE
%global godocs          README.md cmd/ply/README.md

Name:           %{goname}
Release:        %{autorelease}
Summary:        A pure Go Apple Property List transcoder

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/jessevdk/go-flags)
BuildRequires:  golang(gopkg.in/yaml.v1)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md

%gopkgfiles

%changelog
%autochangelog
