# golang-howett-plist.spec
# Generated by go2rpm 1.8.0
%bcond_without check

# https://github.com/DHowett/go-plist
%global goipath         howett.net/plist
%global forgeurl        https://github.com/DHowett/go-plist
Version:                1.0.0

%gometa

%global common_description %{expand:
A pure Go Apple Property List transcoder.}

%global golicenses      LICENSE
%global godocs          README.md cmd/ply/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        A pure Go Apple Property List transcoder

License:        # FIXME
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
rm -r cmd/experimental

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md cmd/ply/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog

