# Generated by go2rpm 1.8.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/googleapis/google-cloud-go-testing
%global goipath         github.com/googleapis/google-cloud-go-testing
%global commit          1c9a4c676720af1d2d964c1b2c866ee500300a15

%gometa

%global common_description %{expand:
Testing Support for the Google Cloud Client Libraries for Go.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md README.md\\\
                        RELEASING.md SECURITY.md datastore/dsiface/README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Testing Support for the Google Cloud Client Libraries for Go

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
# This project is archived and no longer maintained.
# The test provided is an example.
# It currently throws a nilpointer
rm ./examples_test.go
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
