# Generated by go2rpm 1.8.0
%bcond_without check

%global goname          vault

# https://github.com/hashicorp/vault
%global goipath         github.com/hashicorp/vault
Version:                1.11.2

%gometa

%global common_description %{expand:
A tool for secrets management, encryption as a service, and privileged access
management.}

%global golicenses      LICENSE

%global godocs          CHANGELOG.md CONTRIBUTING.md README.md api/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        A tool for secrets management, encryption as a service, and privileged access management

License:        MPL-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/vault %{goipath}
for cmd in plugins/database/redshift/redshift-database-plugin plugins/database/influxdb/influxdb-database-plugin plugins/database/hana/hana-database-plugin plugins/database/mongodb/mongodb-database-plugin plugins/database/cassandra/cassandra-database-plugin plugins/database/mssql/mssql-database-plugin plugins/database/mysql/mysql-legacy-database-plugin plugins/database/mysql/mysql-database-plugin plugins/database/postgresql/postgresql-database-plugin; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CHANGELOG.md CONTRIBUTING.md README.md api/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
