# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/twpayne/go-vfs
%global goipath         github.com/twpayne/go-vfs/v4
Version:                4.1.0

%gometa -f

%global common_description %{expand:
Package vfs provides an abstraction of the os and io packages that is easy to
test.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Package vfs provides an abstraction of the os and io packages that is easy to test

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
