# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/int128/kubelogin
%global goipath         github.com/int128/kubelogin
Version:                1.25.2

%gometa

%global common_description %{expand:
Kubectl plugin for Kubernetes OpenID Connect authentication (kubectl oidc-
login).}

%global golicenses      LICENSE
%global godocs          docs README.md acceptance_test/README.md\\\
                        system_test/README.md

Name:           %{goname}
Release:        %autorelease -b 2
Summary:        Kubectl plugin for Kubernetes OpenID Connect authentication (kubectl oidc-login)

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

Requires:       kubernetes-client

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/kubelogin %{goipath}
for cmd in system_test/login/chromelogin pkg/testing/httpserver; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs README.md acceptance_test/README.md system_test/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog

