# Generated by go2rpm 1.8.2
%bcond_without check

# https://github.com/terraform-docs/terraform-config-inspect
%global goipath         github.com/terraform-docs/terraform-config-inspect
%global commit          9c1f178932fa6a9628dbcc159217224b4cc4c5fb

%gometa -f

%global common_description %{expand:
This is an unmaintained internal fork, refer to main project at
https://github.com/hashicorp/terraform-config-inspect.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Internal fork, refer to main project at https://github.com/hashicorp/terraform-config-inspect for terraform-docs

License:        MPL-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/terraform-config-inspect %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
