# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/DHowett/go-plist
%global goipath         github.com/DHowett/go-plist
Version:                1.0.0

%gometa

%global common_description %{expand:
A pure Go Apple Property List transcoder.}

%global golicenses      LICENSE
%global godocs          README.md cmd/ply/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A pure Go Apple Property List transcoder

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md cmd/ply/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed May 25 2022 Anthony Rabbito <hello@anthonyrabbito.com> - 1.0.0-1
- Initial package
