# Generated by go2rpm 1.8.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/fluxcd/go-git-providers
%global goipath         github.com/fluxcd/go-git-providers
Version:                0.8.0

%gometa -f

%global common_description %{expand:
Git provider client for Go.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md README.md\\\
                        DEVELOPMENT.md

Name:           %{goname}
Release:        %autorelease
Summary:        Git provider client for Go

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
