# Generated by go2rpm 1.8.0
%bcond_without check

# https://github.com/mozilla/sops
%global goipath         go.mozilla.org/sops/v3
%global forgeurl        https://github.com/mozilla/sops
Version:                3.7.3

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another pacage,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa

%global goname sops

%global common_description %{expand:
Simple and flexible tool for managing secrets.}

%global golicenses      LICENSE shamir/LICENSE
%global godocs          examples CHANGELOG.rst CODE_OF_CONDUCT.md\\\
                        CONTRIBUTING.md README.rst example.txt age/keys.txt\\\
                        shamir/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Simple and flexible tool for managing secrets

License:        MPL-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE shamir/LICENSE
%doc examples CHANGELOG.rst CODE_OF_CONDUCT.md CONTRIBUTING.md README.rst
%doc example.txt age/keys.txt shamir/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
