# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/twpayne/go-shell
%global goipath         github.com/twpayne/go-shell
Version:                0.3.1

%gometa -f

%global common_description %{expand:
Go-shell returns a user's shell across multiple platforms.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go-shell returns a user's shell across multiple platforms

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
# Test binary is removed. If needed please open a RHBZ.
rm -r cmd/shell

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
