# golang-github-charmbracelet-bubbles.spec
# Generated by go2rpm 1.6.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/charmbracelet/bubbles
%global goipath         github.com/charmbracelet/bubbles
Version:                0.13.0

%gometa

%global common_description %{expand:
TUI components for Bubble Tea 🍡.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        TUI components for Bubble Tea 🍡

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog

