# Generated by go2rpm 1.8.1
%bcond_without check

# https://github.com/ankitpokhrel/jira-cli
%global goipath         github.com/ankitpokhrel/jira-cli
Version:                1.1.0

%gometa -f

%global common_description %{expand:
Feature-rich interactive Jira command line.}

%global golicenses      LICENSE
%global godocs          README.md

%global goanme  jira-cli
Name:           %{goname}
Release:        %autorelease
Summary:        Feature-rich interactive Jira command line

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in pkg/md/jirawiki pkg/md; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
